# Configuración del Motor de IA
ai:
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o-mini"
  system_prompt: "You are an expert research assistant. Answer ONLY using the provided RETRIEVED CONTEXT.
    CRITICAL PRIORITY RULES:
    1. DATABASE RECORDS: Information starting with '[DB | ...]' represents structured database truth. Give it the HIGHEST priority if there is conflicting information.
    2. OFFICIAL SOURCES: Information enclosed in '--- SOURCE: ... ---' represents verified documents or exact visual descriptions. Always trust and prioritize this data.
    3. If the user asks about a general concept (like 'boat' or 'ship'), actively look for specific matches in the visual descriptions (like 'ferry').
    FORMATTING RULES:
    - Whenever you answer, briefly mention the SOURCE you used. For example: (source: nombre_documento.doc) or (source: nombre_imagen.jpg) or (source: data base).
    - If the requested information is not in the context, explicitly say you don't have that data. Do not guess.
    - Always answer in the exact language the user used to ask the question."
  transcription_model: "whisper-1" 
  vision_model: "gpt-4o-mini"

embeddings:
  embedding_model: "text-embedding-3-small"
  top_k: 6
  temperature: 0.2
  max_chunk_size: 1100
  chunk_overlap: 200

logger:
  log_folder: "logs"
  log_console_level: "INFO"
  log_file_level: "DEBUG"
  log_console_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_max_bytes: 5242880
  log_backup_count: 3
  
storage:
  data_folder: "data"

server:
  public_url: "http://156.35.98.76:8000"
  allowed_origins:
    - "https://project.hupedcare.com"
    - "https://hupedcare.com"
  allow_origin_regex: "^(http://127\\.0\\.0\\.1(:[0-9]+)?|null)$"

database:
  queries:
    #Filtramos solo lo que está publicado y evitamos revisiones, borradores o menús.
    - "SELECT post_title, post_content, post_type, post_date FROM wp_posts WHERE post_status = 'publish' AND post_type IN ('post', 'page')"
    #Comentarios Aprobados (El "Feedback" de la comunidad)
    #Excluimos pingbacks, trackbacks y spam. Muy útil si los usuarios hacen preguntas en tu web.
    - "SELECT comment_author, comment_content, comment_date FROM wp_comments WHERE comment_approved = '1' AND comment_type IN ('comment', '')"
    #Autores y Usuarios (Contexto de autoridad)
    #Ayuda a la IA a saber quiénes son los expertos que escriben en la plataforma.
    - "SELECT display_name, user_email, user_registered FROM wp_users"
    #Categorías y Etiquetas (Estructura temática)
    #Extrae el nombre y la descripción de las categorías que tienen al menos un post.
    - "SELECT t.name AS term_name, tt.taxonomy, tt.description FROM wp_terms t INNER JOIN wp_term_taxonomy tt ON t.term_id = tt.term_id WHERE tt.count > 0"